---
title: "Final Project"
author: "Xoog"
---

Welcome to my data science class project's landing page! During this project, I experimented with different facets of data science, ranging from using SQL to access databases to displaying geospatial data and organizing disorganized information. This project served as an introduction to the topic of data science and gave me the opportunity to become hands-on with essential tools and techniques.

I became proficient in SQL during the assignment and learned how to query databases to obtain insightful information from structured data. Another area of focus was mapping, where I discovered how to use tools like Leaflet in R to visualize geographic data and identify spatial patterns and connections. Furthermore, data wrangling was essential to the project's success as I cleaned and ready information for analysis, addressing issues such as missing and inconsistent formatting.


My thoughts on this project were filled with excitement and curiosity. Each step of the journey brought new discoveries and insights, reinforcing my passion for data science and its potential to drive improvements. The ability to transform unprocessed data into useful insights gave me confidence as I made my way through the challenges of data manipulation and visualization.

An overview of my project is available on this website, along with a list of the abilities and information I have gained thus far. Each component offers a peek into the various facets of data science that are investigated throughout the project, ranging from interactive maps and SQL queries to data wrangling strategies. Come along with me as we delve into the intriguing field of data science on this exploration and discovery journey!

           